# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\Ballscrew\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cal = QtWidgets.QWidget()
        self.tab_cal.setObjectName("tab_cal")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_cal)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_cal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_calicurate = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_calicurate.setObjectName("pushButton_calicurate")
        self.horizontalLayout_2.addWidget(self.pushButton_calicurate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView_conditions = DictTableView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_conditions.sizePolicy().hasHeightForWidth())
        self.tableView_conditions.setSizePolicy(sizePolicy)
        self.tableView_conditions.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableView_conditions.setObjectName("tableView_conditions")
        self.verticalLayout.addWidget(self.tableView_conditions)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_cal)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_csv = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_csv.setObjectName("pushButton_csv")
        self.horizontalLayout_4.addWidget(self.pushButton_csv)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tableView_result = DictTableView(self.groupBox_2)
        self.tableView_result.setObjectName("tableView_result")
        self.verticalLayout_2.addWidget(self.tableView_result)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_cal, "")
        self.tab_ballscrew = QtWidgets.QWidget()
        self.tab_ballscrew.setObjectName("tab_ballscrew")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_ballscrew)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_ballscrew = DictTableView(self.tab_ballscrew)
        self.tableView_ballscrew.setObjectName("tableView_ballscrew")
        self.verticalLayout_5.addWidget(self.tableView_ballscrew)
        self.tabWidget.addTab(self.tab_ballscrew, "")
        self.tab_motor = QtWidgets.QWidget()
        self.tab_motor.setObjectName("tab_motor")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_motor)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableView_motor = DictTableView(self.tab_motor)
        self.tableView_motor.setObjectName("tableView_motor")
        self.verticalLayout_4.addWidget(self.tableView_motor)
        self.tabWidget.addTab(self.tab_motor, "")
        self.tab_coupling = QtWidgets.QWidget()
        self.tab_coupling.setObjectName("tab_coupling")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_coupling)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView_coupling = DictTableView(self.tab_coupling)
        self.tableView_coupling.setObjectName("tableView_coupling")
        self.verticalLayout_3.addWidget(self.tableView_coupling)
        self.tabWidget.addTab(self.tab_coupling, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "条件"))
        self.pushButton_calicurate.setText(_translate("MainWindow", "計算"))
        self.groupBox_2.setTitle(_translate("MainWindow", "結果"))
        self.pushButton_csv.setText(_translate("MainWindow", "csv出力"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cal), _translate("MainWindow", "計算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ballscrew), _translate("MainWindow", "ボールねじ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_motor), _translate("MainWindow", "モーター"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_coupling), _translate("MainWindow", "カップリング"))

from model import DictTableView
